const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');const ts=require('typescript');
function setup(chip='ESP32',capacity='4MB', failConnect=false) {
 const calls=[]; const context={exports:{},require:name=>name==='esptool-js'?{Transport:class {async disconnect(){calls.push('disconnect');}},ESPLoader:class{chip={CHIP_NAME:chip,IMAGE_CHIP_ID:0,BOOTLOADER_FLASH_OFFSET:4096};async connect(mode,attempts){calls.push(['attempts',mode,attempts]);if(failConnect && failConnect!=='stub')throw new Error(typeof failConnect==='string'?failConnect:'Failed to connect');}async main(mode){calls.push('connect');if(failConnect){await this.connect(mode);throw new Error(typeof failConnect==='string'?failConnect:'Failed to connect');}if(mode==='no_reset')calls.push('manual');}async detectFlashSize(){return capacity;}async writeFlash(options){calls.push('write');assert.equal(options.eraseAll,false);assert.equal(typeof options.calculateMD5Hash,'function');}async after(){calls.push('reset');}}}:{default:{ArrayBuffer:{hash:()=>''}}},Uint8Array,Error};
 const source=fs.readFileSync('src/app/project-flasher.ts','utf8');vm.runInNewContext(ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,context);
 const data=new Uint8Array(8192);data[4096]=233;
 return {flash:context.exports.flashProject,calls,data};
}
test('wrong connected chip never writes and disconnects',async()=>{const {flash,calls,data}=setup('ESP32-S3');await assert.rejects(flash({}, {chip:'ESP32',format:'MERGED'},[{data,address:0}],()=>{},()=>{},()=>false),/Modelo conectado/);assert.deepEqual(calls,['connect','disconnect']);});
test('valid firmware checks capacity, writes, resets and releases port',async()=>{const {flash,calls,data}=setup();await flash({}, {chip:'ESP32',format:'MERGED'},[{data,address:0}],()=>{},()=>{},()=>false);assert.deepEqual(calls,['connect','write','reset','disconnect']);});
test('oversized or wrong binary fails before writing',async()=>{const {flash,calls,data}=setup('ESP32','4KB');await assert.rejects(flash({}, {chip:'ESP32',format:'MERGED'},[{data,address:0}],()=>{},()=>{},()=>false),/mem/);assert.equal(calls.includes('write'),false);const second=setup();second.data[4108]=9;await assert.rejects(second.flash({}, {chip:'ESP32',format:'MERGED'},[{data:second.data,address:0}],()=>{},()=>{},()=>false),/outro chip/);assert.equal(second.calls.includes('write'),false);});

 test('failed connection has actionable BOOT guidance and releases the port',async()=>{const {flash,calls,data}=setup('ESP32','4MB',true);await assert.rejects(flash({}, {chip:'ESP32',format:'MERGED'},[{data,address:0}],()=>{},()=>{},()=>false),/BOOT/);assert.deepEqual(calls,['connect',['attempts','default_reset',2],'disconnect']);});
 test('manual mode skips automatic reset and reports stages',async()=>{const {flash,calls,data}=setup();const stages=[];await flash({}, {chip:'ESP32',format:'MERGED'},[{data,address:0}],()=>{},()=>{},()=>false,true,s=>stages.push(s));assert.deepEqual(calls,['connect','manual','write','reset','disconnect']);assert.equal(stages.length,4);});
 test('cancelled preparation never writes firmware',async()=>{const {flash,calls,data}=setup();await assert.rejects(flash({}, {chip:'ESP32',format:'MERGED'},[{data,address:0}],()=>{},()=>{},()=>true),/cancelada/);assert.equal(calls.includes('write'),false);assert.equal(calls.at(-1),'disconnect');});

test('serial open failure identifies busy port before suggesting boot mode',async()=>{const {flash,calls,data}=setup('ESP32','4MB',"Failed to execute 'open' on 'SerialPort': Failed to open serial port.");await assert.rejects(flash({}, {chip:'ESP32',format:'MERGED'},[{data,address:0}],()=>{},()=>{},()=>false),error=>/Monitor Serial/.test(error.message)&&!/BOOT/.test(error.message));assert.equal(calls.includes('write'),false);});

test('unreadable flash never falls back to assumed capacity or writes',async()=>{const {flash,calls,data}=setup('ESP32',null);await assert.rejects(flash({}, {chip:'ESP32',format:'MERGED'},[{data,address:0}],()=>{},()=>{},()=>false),/identificar/);assert.equal(calls.includes('write'),false);assert.equal(calls.at(-1),'disconnect');});
test('installed ESP32-C6 driver uses the corrected SPI flash register',async()=>{const {ESP32C6ROM}=await import('esptool-js/lib/targets/esp32c6.js');const chip=new ESP32C6ROM();assert.equal(chip.SPI_REG_BASE,0x60003000);assert.equal(chip.IMAGE_CHIP_ID,13);assert.equal(chip.BOOTLOADER_FLASH_OFFSET,0);});

test('failure after connection preserves the device error instead of blaming BOOT',async()=>{const {flash,calls,data}=setup('ESP32','4MB','stub');await assert.rejects(flash({}, {chip:'ESP32',format:'MERGED'},[{data,address:0}],()=>{},()=>{},()=>false),error=>error.message.includes('stub')&&!error.message.includes('BOOT'));assert.equal(calls.includes('write'),false);});
